POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username" : "anhdungyb99",
    "password" : "dung1999"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username" : "anhdungyb99",
    "password" : "dung1999"
}

###
POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzJjNzZmMDUwNTVlNTAwYjcwZmFlYzUiLCJpYXQiOjE2NjU1OTAxMjV9.f38Z81rgXkX3N9fpxRG-v3XQsblOiDGJO2TI3RzBgPY

{
    "title" : "post4",
    "description" : "post4",
    "url" : "shoppe.com",
    "status" : "TO LEARN"
}

###
PUT http://localhost:5000/api/posts/63356cdf6bbde80bedce1006
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzIxOWZhOTdkN2RlMWU0ZTkxOWYyZGYiLCJpYXQiOjE2NjMxNjIzMzd9.BCKTDUKfcNuonFVYShwQvPfjm9LU5lSZ5TIc5TZoNKs

{
    "title" : "2343434343",
    "description" : "aaaa ",
    "url" : "shoppe.com",
    "status" : "TO LEARN"
}

###
DELETE http://localhost:5000/api/posts/635836e20b49085691fa48d2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzIxOWZhOTdkN2RlMWU0ZTkxOWYyZGYiLCJpYXQiOjE2NjMxNjIzMzd9.BCKTDUKfcNuonFVYShwQvPfjm9LU5lSZ5TIc5TZoNKs

###
GET http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzJjNzZmMDUwNTVlNTAwYjcwZmFlYzUiLCJpYXQiOjE2NjU1OTAwNzJ9.FQLRFmx2hExYd2Ui0UvYTkZw_zeuQsBUaiYtzuYqXKc

###
POST http://localhost:5000/api/auth/login-google
Content-Type: application/json

###
GET http://localhost:5000/api/courses/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzJjNzZmMDUwNTVlNTAwYjcwZmFlYzUiLCJpYXQiOjE2Njc0NzIwMzF9.-bwaz-wEYtyAsuqJrECoyIUEm_0csTgcqjoWhHui3YA

###
POST http://localhost:5000/api/courses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzJjNzZmMDUwNTVlNTAwYjcwZmFlYzUiLCJpYXQiOjE2Njc0NzIwMzF9.-bwaz-wEYtyAsuqJrECoyIUEm_0csTgcqjoWhHui3YA

{
    "description" : "abcasd"
}

###
DELETE http://localhost:5000/api/courses/6363d50bc3eb4c8339bbc0bd
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzJjNzZmMDUwNTVlNTAwYjcwZmFlYzUiLCJpYXQiOjE2Njc0NzIwMzF9.-bwaz-wEYtyAsuqJrECoyIUEm_0csTgcqjoWhHui3YA

###
PUT http://localhost:5000/api/courses/6363d43932aea925fb97c6a4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzIxOWZhOTdkN2RlMWU0ZTkxOWYyZGYiLCJpYXQiOjE2NjMxNjIzMzd9.BCKTDUKfcNuonFVYShwQvPfjm9LU5lSZ5TIc5TZoNKs

{
    "name" : "aaaa",
    "description" : "aaaa "
    
}

###
GET http://localhost:5000/api/users/student
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzJjNzZmMDUwNTVlNTAwYjcwZmFlYzUiLCJpYXQiOjE2Njc0NzIwMzF9.-bwaz-wEYtyAsuqJrECoyIUEm_0csTgcqjoWhHui3YA